--liquibase formatted sql

--changeset heatmap:002-create-ai-tool
--comment: реестр AI-инструментов PDLC. Роль и сегмент - множественные, вынесены в отдельные
--comment: таблицы tool_role / tool_segment (см. 003-create-tool-role-segment.sql).
--comment: description - VARCHAR без указания длины (в H2 это практически неограниченный размер);
--comment: CLOB здесь не подходит - Hibernate не даёт использовать lower() (нужен для поиска) на CLOB-поле.
--comment: плашки "Топ" нет отдельной колонкой - она вычисляется на лету (см. ToolService.computeTopIds).
CREATE TABLE ai_tool
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR      NOT NULL,
    stage          VARCHAR(16)  NOT NULL DEFAULT 'ACCESS',
    status         VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    framework      VARCHAR(64)  NOT NULL,
    source_label   VARCHAR(128) NOT NULL,
    owner_name     VARCHAR(255) NOT NULL,
    downloads      INTEGER      NOT NULL DEFAULT 0,
    dau            INTEGER,
    efficiency_pct INTEGER      NOT NULL DEFAULT 0,
    views          BIGINT       NOT NULL DEFAULT 0,
    rating_sum     BIGINT       NOT NULL DEFAULT 0,
    ratings_count  INTEGER      NOT NULL DEFAULT 0,
    created_by     BIGINT,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rejection_reason VARCHAR(1000),
    CONSTRAINT fk_ai_tool_created_by FOREIGN KEY (created_by) REFERENCES app_user (id) ON DELETE SET NULL,
    CONSTRAINT ck_ai_tool_stage CHECK (stage IN ('ACCESS', 'USAGE', 'HABIT', 'STANDARD')),
    CONSTRAINT ck_ai_tool_status CHECK (status IN ('PENDING', 'PUBLISHED', 'REJECTED')),
    CONSTRAINT ck_ai_tool_efficiency CHECK (efficiency_pct BETWEEN 0 AND 100)
);

--changeset heatmap:002-ai-tool-idx-stage
CREATE INDEX idx_ai_tool_stage ON ai_tool (stage);

--changeset heatmap:002-ai-tool-idx-status
CREATE INDEX idx_ai_tool_status ON ai_tool (status);

--changeset heatmap:002-ai-tool-idx-views
CREATE INDEX idx_ai_tool_views ON ai_tool (views);
