--liquibase formatted sql

--changeset heatmap:004-create-impact-block
--comment: блоки секции "Влияние на метрики" (Habit / Process Standard)
CREATE TABLE impact_block
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(16)  NOT NULL,
    icon         VARCHAR(8)   NOT NULL DEFAULT '',
    title        VARCHAR(255) NOT NULL,
    badge_text   VARCHAR(64)  NOT NULL,
    badge_status VARCHAR(16)  NOT NULL DEFAULT 'ACHIEVED',
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT uq_impact_block_code UNIQUE (code),
    CONSTRAINT ck_impact_block_badge CHECK (badge_status IN ('ACHIEVED', 'MISSED'))
);

--changeset heatmap:004-create-impact-row
--comment: строки метрик внутри блока
CREATE TABLE impact_row
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id      BIGINT       NOT NULL,
    label         VARCHAR(255) NOT NULL,
    metric_value  VARCHAR(64)  NOT NULL,
    color_variant VARCHAR(16)  NOT NULL DEFAULT 'DEFAULT',
    is_footer     BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_impact_row_block FOREIGN KEY (block_id) REFERENCES impact_block (id) ON DELETE CASCADE,
    CONSTRAINT ck_impact_row_color CHECK (color_variant IN ('DEFAULT', 'BLUE', 'GREEN', 'GOLD'))
);
